name: storage_example
description: Demonstrates how to use the storage plugin.
publish_to: "none"

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  storage:
    path: ../

flutter:
  uses-material-design: true
