name: storage_example
description: Demonstrates how to use the storage plugin.
publish_to: "none"

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  storage:
    path: ../

  path_provider: ^1.3.0
  shared_preferences: ^0.5.3+4
  flutter_secure_storage: ^3.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
