name: storage
description: A flutter plugin for storing things :)
version: 0.0.1
author: Compass
homepage: compass.com

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^0.4.1
  shared_preferences: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  uuid: ^1.0.3

flutter:
  plugin:
    androidPackage: com.compass.storage
    pluginClass: StoragePlugin
