name: storage
description: A flutter plugin for storing things :)
version: 0.1.0
author: Compass <wes@compass.com>
homepage: http://compass.com

environment:
  sdk: ">=2.3.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  shared_preferences: ^0.5.6
  flutter_secure_storage: ^3.3.1+1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_api:
  uuid:
  mockito:

flutter:
  plugin:
    androidPackage: com.compass.storage
    pluginClass: StoragePlugin
